#!/bin/bash

NOCOLOR='\033[0m'
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'

ERROR () {
  echo -e "${RED}ERROR${NOCOLOR}"
  exit
}

DONE () {
  echo -e "${GREEN}DONE${NOCOLOR}"
  sleep 1
}

if [[ $EUID -ne 0 ]]
then
	echo -e "${RED}Debese ejecutar como usuario con privilegios${NOCOLOR}"
	exit
fi

echo -e "${BLUE}>>Carpeta destino ISO:${NOCOLOR}\c"
read -e -i $(pwd) RUTAD

echo -e "${BLUE}\n>>Instalando paquetes necesarios${NOCOLOR}"
sleep 2
pacman --noconfirm -Sy archiso && DONE || ERROR

echo -e "${BLUE}\n>>Creando ficheros de configuracion de la ISO${NOCOLOR}"
rm -rf /iso
mkdir -p /iso/perfil
cp -rv /usr/share/archiso/configs/releng/* /iso/perfil || ERROR
rm /iso/perfil/efiboot/loader/entries/02*
cp -rv iso/* /iso/perfil || ERROR
cd ..
cp -rv installer /iso/perfil/airootfs/root/
cd /iso/perfil/airootfs/root
if [[ $1 = "--online" ]]
then
	sed "s/iso_version=\"\$(date +%Y.%m.%d)\"/iso_version=\"$2\"/" iso/profiledef.sh > /iso/perfil/profiledef.sh
	echo -e "\nrm -rf installer\ngit clone -b $2 https://github.com/cambonos/installer" > .zshrc
fi
echo -e "sh installer/parted.sh" >> .zshrc
DONE

echo -e "${BLUE}\n>>Creando la ISO${NOCOLOR}"
sleep 2; cd
mkarchiso -v -w /iso/work -o $RUTAD /iso/perfil && DONE || ERROR

echo -e "${BLUE}\n>>Eliminado ficheros/paquetes innecesarios${NOCOLOR}"
sleep 2
rm -rf /iso
pacman --noconfirm -Rns archiso
DONE
