Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"

    Option "Tapping" "on"
    Option "NaturalScrolling" "true"
    Option "DisableWhileTyping" "true"
    Option "ScrollMethod" "twofinger"
    Option "ClickMethod" "clickfinger"
    Option "AccelSpeed" "0.15"
    Option "HorizontalScrolling" "true"
EndSection
